runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: frontend/css

- url: /js
  static_dir: frontend/js
  
- url: /images
  static_dir: frontend/images

- url: /bootstrap-4.2.1-dist
  static_dir: frontend/bootstrap-4.2.1-dist

- url: /
  static_files: frontend/views/login.html
  upload: frontend/views/login.html

- url: /
  static_files: frontend/views/students.html
  upload: frontend/views/students.html

- url: /
  static_files: frontend/views/teachers.html
  upload: frontend/views/teachers.html

- url: /(.*)
  static_files: frontend/views/\1
  upload: frontend/views/(.*)
